import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { MobileNav } from "@/components/MobileNav";
import { Sidebar } from "@/components/Sldebar";
import Header from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className='flex min-h-screen flex-col bg-gray-50 lg:flex-row'>
          {/* Desktop Sidebar - Hidden on mobile */}
          <div className='hidden lg:block'>
            <Sidebar />
          </div>

          <div className='flex flex-1 flex-col ml-64'>
            {/* Header */}
            <Header />
            {/* Main Content */}

            {children}
            {/* Mobile Navigation - Fixed at bottom */}
            <div className='fixed bottom-0 left-0 z-50 w-full lg:hidden'>
              <MobileNav />
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
